theme: jekyll-theme-slate
author:
  name: Ben Rogers
  url: https://github.com/BenRogersWPG
title: Title of Your Post
defaults:
  - scope:
      path: ""
    values:
      image: /Media/Badges/Sapphire-Reader/sapphire-reader.png
      height: 839
      width: 1405