theme: jekyll-theme-slate
plugins:
    - jekyll-sitemap
author:
  name: Ben Rogers
  url: https://github.com/BenRogersWPG
title: Title of Your Post
description: 🧪 A Complete Test for your eyes 🧪
defaults:
  - scope:
      path: ""
    values:
      image: /Media/Badges/Sapphire-Reader/sapphire-reader.png
    height: 839
    width: 1405
layout:
sitemap: false